# Generated by Django 4.0.3 on 2022-04-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('todo_auth', models.CharField(max_length=100)),
                ('todo_title', models.CharField(max_length=100)),
                ('todo_desc', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': "Todo's",
            },
        ),
    ]
