# Generated by Django 4.0.3 on 2022-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
