# Generated by Django 4.0.3 on 2022-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_todo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(choices=[('Important', 'Important'), ('Urgent', 'Urgent'), ('Top', 'Top')], max_length=100)),
            ],
            options={
                'verbose_name_plural': "Tag's",
            },
        ),
    ]
