# Generated by Django 4.0.3 on 2022-04-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='todo',
            name='status_name',
            field=models.CharField(choices=[('ToDo', 'Todo'), ('InProgress', 'Inprogress'), ('InReview', 'Inreview'), ('Done', 'Done')], default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='tag_name',
            field=models.CharField(choices=[('Important', 'Important'), ('Urgent', 'Urgent'), ('Top', 'Top')], default='NA', max_length=100),
        ),
    ]
