# Generated by Django 4.0.3 on 2022-04-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_delete_tag_todo_status_name_todo_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_id',
        ),
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
